### ISSUE TITLE
Problema com validação de token

### ISSUE THREAD

**Issue by tarikochuery** [tarikochuery/projeto15-burguer-shop-back#9]
Quando o  o id usuário foi armazenado na `res.locals`, no commit #7 há um bug.

No middleware de validação de token há um problema com a variável que é armazenada no `res.locals`. 

Não existe a propriedade id no objeto `decoded`, portanto é armazenado um `undefined`.

Esse id deve ser pego de outra forma, uma vez que a única responsabilidade do jwt é fazer a validação do token.
Minha sugestão é pedir que o usuário envie sempre o email no headers, e a gente resgate esse user pelo email. Podemos até convertê-lo no documento do user, e repassar com `res.locals` para o restante do código. Essa é minha sugestão, mas fica a seu critério @Dickson-Pinheiro.

**Comment by Dickson-Pinheiro** [comment]
issue corrigida com sucesso. O id já está sendo passado corretamente. Obrigado!
